using System;
using System.Collections.Generic;
using System.Text;
using Server;
using Server.Items;
using Server.Misc;

namespace Server.Mobiles
{
    using Server.Custom.LLMNpc;

    // Base for any creature whose dialog is generated by the local LLM.
    // Subclasses set body/stats/outfit and a DefaultPersona; this class wires
    // speech in (HandlesOnSpeech + OnSpeech) and the async request/response loop.
    public abstract class LLMTalkingMobile : BaseCreature
    {
        private string m_Persona;
        private NpcIdentity m_Identity;
        private Dictionary<int, NpcRelationship> m_Relationships;

        public LLMTalkingMobile(AIType ai, FightMode mode, int rangePerception, int rangeFight, double activeSpeed, double passiveSpeed)
            : base(ai, mode, rangePerception, rangeFight, activeSpeed, passiveSpeed)
        {
        }

        public LLMTalkingMobile(Serial serial)
            : base(serial)
        {
        }

        // Persona override; if empty, DefaultPersona is used. Editable via [props.
        [CommandProperty(AccessLevel.GameMaster)]
        public string Persona
        {
            get { return m_Persona; }
            set { m_Persona = value; }
        }

        public abstract string DefaultPersona { get; }

        public virtual bool RespondsToPlayers { get { return true; } }

        // True for the wild, non-townsfolk speakers (orcs, liches, ogres, and the
        // like). Drives NPC-to-NPC chatter: monster speakers banter only with their
        // own kind and in a monster-aware frame, never amiably with townsfolk.
        public virtual bool IsMonsterSpeaker { get { return false; } }

        // A short scene description appended to the system prompt, e.g. mood/locale.
        public virtual string SceneHint { get { return ""; } }

        // Drives which flavor pool an identity is rolled from. Override per trade.
        public virtual string Vocation { get { return "townsperson"; } }

        // The generated, persisted identity. Lazily created the first time it is
        // needed (by which point the mobile has been placed in the world, so its
        // town can be resolved from its location).
        public NpcIdentity Identity
        {
            get
            {
                EnsureIdentity();
                return m_Identity;
            }
        }

        public void EnsureIdentity()
        {
            if (m_Identity != null && m_Identity.Assigned)
                return;

            string town = BritanniaGeography.TownOf(this);
            m_Identity = NpcIdentity.Generate(Vocation, town, this.Female);
        }

        public override bool HandlesOnSpeech(Mobile from)
        {
            if (LLMConfig.Enabled && RespondsToPlayers && from != null && from.Player && from.InRange(this.Location, LLMConfig.HearRange))
                return true;

            return base.HandlesOnSpeech(from);
        }

        public override void OnSpeech(SpeechEventArgs e)
        {
            base.OnSpeech(e);

            if (!LLMConfig.Enabled || !RespondsToPlayers || e == null)
                return;

            Mobile from = e.Mobile;

            if (from == null || from == this || !from.Player || from.Deleted)
                return;

            if (this.Map == null || this.Map == Map.Internal)
                return;

            string text = e.Speech;

            if (string.IsNullOrEmpty(text))
                return;

            text = text.Trim();

            if (text.Length == 0)
                return;

            if (!from.InRange(this.Location, LLMConfig.HearRange))
                return;

            if (!string.IsNullOrEmpty(LLMConfig.AllowedMap) &&
                (this.Map.Name == null || !this.Map.Name.Equals(LLMConfig.AllowedMap, StringComparison.OrdinalIgnoreCase)))
                return;

            Respond(from, text);
        }

        protected virtual string BuildSystemPrompt(Mobile player)
        {
            EnsureIdentity();

            string persona = string.IsNullOrEmpty(m_Persona) ? DefaultPersona : m_Persona;
            NpcIdentity id = m_Identity;

            StringBuilder sb = new StringBuilder();
            sb.Append("You are ");
            sb.Append(string.IsNullOrEmpty(this.Name) ? "an unnamed character" : this.Name);

            if (!string.IsNullOrEmpty(this.Title))
            {
                sb.Append(" ");
                sb.Append(this.Title);
            }

            sb.Append(", ");
            sb.Append(persona);
            sb.Append(". You live in the medieval fantasy realm of Britannia, the world of Ultima Online. ");

            if (id != null)
            {
                sb.Append("You hold your post in the town of ");
                sb.Append(id.Town);
                sb.Append(". ");

                if (!string.IsNullOrEmpty(id.Origin) && id.Origin != id.Town)
                {
                    sb.Append("You hail originally from ");
                    sb.Append(id.Origin);
                    sb.Append(". ");
                }

                if (!string.IsNullOrEmpty(id.Personality))
                {
                    sb.Append("Your temperament is ");
                    sb.Append(id.Personality);
                    sb.Append(". ");
                }

                if (!string.IsNullOrEmpty(id.Backstory))
                {
                    sb.Append(id.Backstory);
                    sb.Append(" ");
                }

                if (!string.IsNullOrEmpty(id.SpeechStyle))
                {
                    sb.Append("You speak in a manner that is ");
                    sb.Append(id.SpeechStyle);
                    sb.Append(". ");
                }

                if (!string.IsNullOrEmpty(id.Motivation))
                {
                    sb.Append("Privately — never say this outright — you are ");
                    sb.Append(id.Motivation);
                    sb.Append(". ");
                }

                if (!string.IsNullOrEmpty(id.Mood))
                {
                    sb.Append("Right now you are ");
                    sb.Append(id.Mood);
                    sb.Append(". ");
                }
            }

            sb.Append("Always stay in character. Reply with at most two short sentences in a medieval, in-world tone. ");
            sb.Append("Never break character, never mention being an AI or a computer, never mention the modern world or that this is a game. ");

            string scene = SceneHint;
            if (!string.IsNullOrEmpty(scene))
            {
                sb.Append(scene);
                sb.Append(" ");
            }

            sb.Append("You are speaking with an adventurer named ");
            sb.Append(string.IsNullOrEmpty(player.Name) ? "a stranger" : player.Name);
            sb.Append(". ");

            // What this NPC already remembers about this specific player. Reflects
            // state from before the current utterance (which is folded in afterward).
            NpcRelationship rel = GetRelationship(player);
            sb.Append(rel == null ? "You have never met them before." : rel.Recap());

            // P10/P11: townsfolk surface today's aim and the talk of the town;
            // wild speakers keep no civic gossip.
            if (!IsMonsterSpeaker)
            {
                string intent = DailyRoutine.IntentionOf(this.Serial.Value);
                if (!string.IsNullOrEmpty(intent))
                {
                    sb.Append(" Today you have a mind for ");
                    sb.Append(intent);
                    sb.Append(".");
                }

                sb.Append(TownGossip.PromptBlock(id != null && !string.IsNullOrEmpty(id.Town)
                    ? id.Town : BritanniaGeography.TownOf(this)));

                // P15: an open parcel-favor this NPC could offer the traveler.
                sb.Append(FavorDirector.PromptBlock(this.Serial.Value, player.Serial.Value));
            }

            // P7/P14: the (closed) action vocabulary — cosmetic gestures for
            // ordinary talkers, the keeper's powers for the Overseer (override).
            sb.Append(ActionInstruction());

            return sb.ToString();
        }

        // ---- action tags (P7 cosmetic; P14 overrides for the Overseer) --------

        protected virtual string ActionInstruction()
        {
            return NpcActions.PromptInstruction();
        }

        protected virtual string ExtractAction(string reply, out string verb)
        {
            return NpcActions.Extract(reply, FavorDirector.OfferVerbs, out verb);
        }

        protected virtual void PerformAction(Mobile player, string verb)
        {
            // A pending favor's [do:offer] takes precedence (P15); anything
            // else falls through to the cosmetic gestures.
            if (!FavorDirector.TryPerformOffer(this, player, verb))
                NpcActions.Perform(this, verb);
        }

        // P15: a delivered favor raises this NPC's regard for the courier —
        // even when the delivery happened a continent away.
        public void RecordFavor(Mobile player)
        {
            if (player == null)
                return;

            NpcRelationship rel = GetOrCreateRelationship(player);

            rel.Disposition += 15;
            if (rel.Disposition > 100)
                rel.Disposition = 100;
        }

        protected virtual void Respond(Mobile player, string text)
        {
            EnsureIdentity();

            int npcSerial = this.Serial.Value;
            int playerSerial = player.Serial.Value;

            // Build from prior state first, then fold this line into memory so the
            // prompt reflects history as it stood when the player started talking.
            List<LLMMessage> history = LLMConversation.Get(npcSerial, playerSerial);
            history.Add(new LLMMessage("user", text));

            string system = BuildSystemPrompt(player);

            NoteInteraction(player, text);

            // P11: a salient line told to a townsperson may enter the town's talk
            // (chance-gated inside). Monsters don't carry civic gossip.
            if (!IsMonsterSpeaker)
            {
                TownGossip.MaybeAddPlayerRumor(this, player, text);

                // P15: an eligible townsperson may roll a parcel-favor to offer
                // (gated inside; asking for work guarantees it).
                FavorDirector.MaybeCreatePending(this, player, text);
            }

            string key = npcSerial.ToString();
            string archetype = (m_Identity != null) ? m_Identity.Archetype : "";
            string region = (m_Identity != null) ? m_Identity.Town : "";

            LLMTalkingMobile mob = this;

            Mobile talker = player;

            LLMClient.TryDispatch(key, system, history, text, region, archetype, npcSerial, delegate(bool ok, string reply)
            {
                if (mob == null || mob.Deleted)
                    return;

                if (!ok || string.IsNullOrEmpty(reply))
                    return;

                // Strip an action tag before speaking/recording; run the action
                // after the words so the gesture (or the Overseer's power) lands
                // on what was just said.
                string verb;
                string spoken = mob.ExtractAction(reply, out verb);

                LLMConversation.Record(npcSerial, playerSerial, "user", text);
                LLMConversation.Record(npcSerial, playerSerial, "assistant", spoken);

                if (spoken.Length > 0)
                    mob.SpeakReply(spoken);

                mob.PerformAction(talker, verb);
            });
        }

        // ---- persistent relationship tracking -------------------------------

        private void EnsureRelationships()
        {
            if (m_Relationships == null)
                m_Relationships = new Dictionary<int, NpcRelationship>();
        }

        private NpcRelationship GetRelationship(Mobile player)
        {
            if (player == null)
                return null;

            EnsureRelationships();

            NpcRelationship rel;
            if (m_Relationships.TryGetValue(player.Serial.Value, out rel))
                return rel;

            return null;
        }

        private NpcRelationship GetOrCreateRelationship(Mobile player)
        {
            EnsureRelationships();

            int ps = player.Serial.Value;

            NpcRelationship rel;
            if (!m_Relationships.TryGetValue(ps, out rel))
            {
                rel = new NpcRelationship();
                m_Relationships[ps] = rel;
            }

            return rel;
        }

        private void NoteInteraction(Mobile player, string text)
        {
            if (player == null)
                return;

            NpcRelationship rel = GetOrCreateRelationship(player);
            rel.Note(text);

            if (m_Identity != null)
                m_Identity.DriftMood();
        }

        // GM-facing summary of who this NPC remembers, one line per player.
        public List<string> MemoryLines()
        {
            List<string> lines = new List<string>();

            if (m_Relationships == null || m_Relationships.Count == 0)
            {
                lines.Add("(no one remembered yet)");
                return lines;
            }

            foreach (KeyValuePair<int, NpcRelationship> kv in m_Relationships)
            {
                NpcRelationship rel = kv.Value;
                Mobile pl = World.FindMobile((Serial)kv.Key);
                string who = (pl != null && !string.IsNullOrEmpty(pl.Name)) ? pl.Name : ("#" + kv.Key);

                string topics = rel.TopicSummary();
                string line = who + ": " + rel.Conversations + " talk(s), " + rel.Lines +
                    " line(s), disposition " + rel.Disposition;

                if (topics.Length > 0)
                    line += " — recalls " + topics;

                lines.Add(line);
            }

            return lines;
        }

        protected virtual void SpeakReply(string reply)
        {
            this.Say(reply);
        }

        public override void OnDelete()
        {
            base.OnDelete();
            LLMConversation.ClearNpc(this.Serial.Value);
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);

            writer.Write((int)2); // version
            writer.Write(m_Persona);

            // identity
            bool hasId = m_Identity != null;
            writer.Write(hasId);
            if (hasId)
                m_Identity.Serialize(writer);

            // relationships
            int n = m_Relationships == null ? 0 : m_Relationships.Count;
            writer.Write(n);

            if (m_Relationships != null)
            {
                foreach (KeyValuePair<int, NpcRelationship> kv in m_Relationships)
                {
                    writer.Write(kv.Key);
                    kv.Value.Serialize(writer);
                }
            }
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);

            int version = reader.ReadInt();

            if (version >= 1)
                m_Persona = reader.ReadString();

            m_Relationships = new Dictionary<int, NpcRelationship>();

            if (version >= 2)
            {
                bool hasId = reader.ReadBool();
                if (hasId)
                {
                    m_Identity = new NpcIdentity();
                    m_Identity.Deserialize(reader);
                }

                int n = reader.ReadInt();
                for (int i = 0; i < n; i++)
                {
                    int ps = reader.ReadInt();
                    NpcRelationship rel = new NpcRelationship();
                    rel.Deserialize(reader);
                    m_Relationships[ps] = rel;
                }
            }
        }
    }

    // ----- Concrete personas -------------------------------------------------

    // A passive human townsperson.
    public class LLMVillager : LLMTalkingMobile
    {
        [Constructable]
        public LLMVillager()
            : base(AIType.AI_Animal, FightMode.None, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x3B2;
            InitHuman();
            InitStats(60, 60, 25);

            if (Female)
                AddItem(new PlainDress(Utility.RandomNeutralHue()));
            else
                AddItem(new Shirt(Utility.RandomNeutralHue()));

            AddItem(new ShortPants(Utility.RandomNeutralHue()));
            AddItem(new Shoes(Utility.RandomNeutralHue()));

            Utility.AssignRandomHair(this);
        }

        public LLMVillager(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "a humble villager who tends fields and knows the local gossip"; }
        }

        public override string Vocation { get { return "villager"; } }

        public override string SceneHint
        {
            get { return "You go about your daily work among the cottages and fields."; }
        }

        protected void InitHuman()
        {
            Female = Utility.RandomBool();
            Body = Female ? 0x191 : 0x190;
            Name = NameList.RandomName(Female ? "female" : "male");
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // The town blacksmith.
    public class LLMBlacksmith : LLMTalkingMobile
    {
        [Constructable]
        public LLMBlacksmith()
            : base(AIType.AI_Animal, FightMode.None, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x3B2;

            Female = Utility.RandomBool();
            Body = Female ? 0x191 : 0x190;
            Name = NameList.RandomName(Female ? "female" : "male");
            Title = "the blacksmith";

            InitStats(80, 70, 40);

            AddItem(new Shirt(Utility.RandomNeutralHue()));
            AddItem(new ShortPants(Utility.RandomNeutralHue()));
            AddItem(new HalfApron(Utility.RandomNeutralHue()));
            AddItem(new Boots(Utility.RandomNeutralHue()));

            Utility.AssignRandomHair(this);
        }

        public LLMBlacksmith(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "the town blacksmith, gruff and proud of your craft, you forge weapons and armor and speak plainly"; }
        }

        public override string Vocation { get { return "blacksmith"; } }

        public override string SceneHint
        {
            get { return "You stand by your forge and anvil, soot on your hands."; }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // The keeper of the local tavern.
    public class LLMTavernKeeper : LLMTalkingMobile
    {
        [Constructable]
        public LLMTavernKeeper()
            : base(AIType.AI_Animal, FightMode.None, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x3B2;

            Female = Utility.RandomBool();
            Body = Female ? 0x191 : 0x190;
            Name = NameList.RandomName(Female ? "female" : "male");
            Title = "the tavern keeper";

            InitStats(65, 60, 35);

            if (Female)
                AddItem(new PlainDress(Utility.RandomNeutralHue()));
            else
                AddItem(new Shirt(Utility.RandomNeutralHue()));

            AddItem(new ShortPants(Utility.RandomNeutralHue()));
            AddItem(new HalfApron(Utility.RandomNeutralHue()));
            AddItem(new Shoes(Utility.RandomNeutralHue()));

            Utility.AssignRandomHair(this);
        }

        public LLMTavernKeeper(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "the warm and talkative keeper of the local tavern, full of rumors, ale, and welcome for travelers"; }
        }

        public override string Vocation { get { return "tavernkeeper"; } }

        public override string SceneHint
        {
            get { return "You are behind the bar of a cozy, candle-lit tavern."; }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // The keeper of the town bank. Town-aware identity makes the banker of
    // Britain a different soul from the banker of Vesper.
    public class LLMBanker : LLMTalkingMobile
    {
        [Constructable]
        public LLMBanker()
            : base(AIType.AI_Animal, FightMode.None, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x3B2;

            Female = Utility.RandomBool();
            Body = Female ? 0x191 : 0x190;
            Name = NameList.RandomName(Female ? "female" : "male");
            Title = "the banker";

            InitStats(60, 70, 45);

            if (Female)
                AddItem(new FancyDress(Utility.RandomNeutralHue()));
            else
                AddItem(new FancyShirt(Utility.RandomNeutralHue()));

            AddItem(new LongPants(Utility.RandomNeutralHue()));
            AddItem(new Shoes(Utility.RandomNeutralHue()));

            Utility.AssignRandomHair(this);
        }

        public LLMBanker(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "a banker of the realm who safeguards the gold and goods of all who walk through your door, mindful of coin and discreet about your patrons"; }
        }

        public override string Vocation { get { return "banker"; } }

        public override string SceneHint
        {
            get { return "You stand behind the counter of the bank, ledgers and a locked strongbox close at hand."; }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // A hostile creature that taunts before (and while) it fights.
    [CorpseName("an orcish corpse")]
    public class LLMFeralOrc : LLMTalkingMobile
    {
        [Constructable]
        public LLMFeralOrc()
            : base(AIType.AI_Melee, FightMode.Closest, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x21; // angry red
            Name = NameList.RandomName("orc");
            Title = "the savage";
            Body = 17;
            BaseSoundID = 0x45A;

            SetStr(96, 120);
            SetDex(81, 105);
            SetInt(36, 60);

            SetHits(58, 72);
            SetDamage(5, 7);

            SetDamageType(ResistanceType.Physical, 100);

            SetResistance(ResistanceType.Physical, 25, 30);
            SetResistance(ResistanceType.Fire, 20, 30);
            SetResistance(ResistanceType.Cold, 10, 20);
            SetResistance(ResistanceType.Poison, 10, 20);
            SetResistance(ResistanceType.Energy, 20, 30);

            SetSkill(SkillName.MagicResist, 50.1, 75.0);
            SetSkill(SkillName.Tactics, 55.1, 80.0);
            SetSkill(SkillName.Wrestling, 50.1, 70.0);

            Fame = 1500;
            Karma = -1500;
            VirtualArmor = 28;
        }

        public LLMFeralOrc(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "a savage orc raider who menaces and taunts intruders in broken, brutish common tongue, hungry for a fight"; }
        }

        public override string Vocation { get { return "raider"; } }

        public override bool IsMonsterSpeaker { get { return true; } }

        public override string SceneHint
        {
            get { return "You bare your tusks at a trespasser in your foul camp. Be threatening, not friendly."; }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // A lich: an undead sorcerer-king, drunk on its own deathless power. The
    // megalomaniac of the bestiary — it does not threaten so much as PRONOUNCE,
    // certain every mortal exists to serve, kneel before, or be unmade by it.
    [CorpseName("a liche's corpse")]
    public class LLMLich : LLMTalkingMobile
    {
        [Constructable]
        public LLMLich()
            : base(AIType.AI_NecroMage, FightMode.Closest, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x3F; // a cold, baleful blue-violet
            Name = NameList.RandomName("male");
            Title = "the Deathless";
            Body = 24;
            BaseSoundID = 0x3E9;

            SetStr(171, 200);
            SetDex(126, 145);
            SetInt(276, 305);

            SetHits(103, 120);
            SetDamage(24, 26);

            SetDamageType(ResistanceType.Physical, 10);
            SetDamageType(ResistanceType.Cold, 40);
            SetDamageType(ResistanceType.Energy, 50);

            SetResistance(ResistanceType.Physical, 40, 60);
            SetResistance(ResistanceType.Fire, 20, 30);
            SetResistance(ResistanceType.Cold, 50, 60);
            SetResistance(ResistanceType.Poison, 55, 65);
            SetResistance(ResistanceType.Energy, 40, 50);

            SetSkill(SkillName.Necromancy, 89, 99.1);
            SetSkill(SkillName.SpiritSpeak, 90.0, 99.0);
            SetSkill(SkillName.EvalInt, 100.0);
            SetSkill(SkillName.Magery, 70.1, 80.0);
            SetSkill(SkillName.Meditation, 85.1, 95.0);
            SetSkill(SkillName.MagicResist, 80.1, 100.0);
            SetSkill(SkillName.Tactics, 70.1, 90.0);

            Fame = 8000;
            Karma = -8000;
            VirtualArmor = 50;
        }

        public LLMLich(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get
            {
                return "an ancient lich, an undead sorcerer-king who long ago traded a beating heart for power without end. " +
                       "You are a colossal megalomaniac: serenely, absolutely certain of your own supremacy, you regard every living " +
                       "thing as a lesser, fleeting thing that exists to serve you, to kneel, or to be unmade. You do not rage — you " +
                       "PRONOUNCE, grandiose and imperious, naming the mortal before you a worm, a subject, or a future servant of your " +
                       "deathless dominion. Mercy is beneath you; so is haste";
            }
        }

        public override string Vocation { get { return "lich"; } }

        public override bool IsMonsterSpeaker { get { return true; } }

        public override string SceneHint
        {
            get
            {
                return "You hold court amid the dust of your tomb, where a mortal has dared to intrude. Be grandiose, cold, and " +
                       "supremely contemptuous — never friendly, never afraid. Speak as a god-king addressing an insect.";
            }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // An ogre: a great dim-witted brute, all hunger and menace, mangling the
    // common tongue into a few heavy, grunted words.
    [CorpseName("an ogre corpse")]
    public class LLMOgre : LLMTalkingMobile
    {
        [Constructable]
        public LLMOgre()
            : base(AIType.AI_Melee, FightMode.Closest, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x21; // angry red
            Name = "an ogre";
            Title = "the brute";
            Body = 1;
            BaseSoundID = 427;

            SetStr(166, 195);
            SetDex(46, 65);
            SetInt(46, 70);

            SetHits(100, 117);
            SetMana(0);
            SetDamage(9, 11);

            SetDamageType(ResistanceType.Physical, 100);

            SetResistance(ResistanceType.Physical, 30, 35);
            SetResistance(ResistanceType.Fire, 15, 25);
            SetResistance(ResistanceType.Cold, 15, 25);
            SetResistance(ResistanceType.Poison, 15, 25);
            SetResistance(ResistanceType.Energy, 25);

            SetSkill(SkillName.MagicResist, 55.1, 70.0);
            SetSkill(SkillName.Tactics, 60.1, 70.0);
            SetSkill(SkillName.Wrestling, 70.1, 80.0);

            Fame = 3000;
            Karma = -3000;
            VirtualArmor = 32;
        }

        public LLMOgre(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "a huge, dim-witted ogre, slow of thought and quick to hunger, who menaces in a few heavy, broken words of the common tongue and thinks mostly of smashing and eating"; }
        }

        public override string Vocation { get { return "ogre"; } }

        public override bool IsMonsterSpeaker { get { return true; } }

        public override string SceneHint
        {
            get { return "You loom over a little thing that has wandered too close to your club. Speak in short, broken, brutish grunts — three or four crude words. Be threatening and stupid, not clever."; }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // A lizardman: a primitive cold-blooded reptilian, wary and territorial,
    // hissing broken speech at warm-bloods who stray into its marsh.
    [CorpseName("a lizardman corpse")]
    public class LLMLizardman : LLMTalkingMobile
    {
        [Constructable]
        public LLMLizardman()
            : base(AIType.AI_Melee, FightMode.Closest, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x21;
            Name = NameList.RandomName("lizardman");
            Title = "the marshborn";
            Body = Utility.RandomList(35, 36);
            BaseSoundID = 417;

            SetStr(96, 120);
            SetDex(86, 105);
            SetInt(36, 60);

            SetHits(58, 72);
            SetDamage(5, 7);

            SetDamageType(ResistanceType.Physical, 100);

            SetResistance(ResistanceType.Physical, 25, 30);
            SetResistance(ResistanceType.Fire, 15, 20);
            SetResistance(ResistanceType.Cold, 5, 10);
            SetResistance(ResistanceType.Poison, 10, 20);
            SetResistance(ResistanceType.Energy, 10, 15);

            SetSkill(SkillName.MagicResist, 35.1, 50.0);
            SetSkill(SkillName.Tactics, 55.1, 70.0);
            SetSkill(SkillName.Wrestling, 50.1, 65.0);

            Fame = 1000;
            Karma = -1000;
            VirtualArmor = 24;
        }

        public LLMLizardman(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "a primitive lizardman of the marshes, cold-blooded, wary and fiercely territorial, who hisses warnings in broken, sibilant common at warm-bloods who trespass on your waters"; }
        }

        public override string Vocation { get { return "lizardman"; } }

        public override bool IsMonsterSpeaker { get { return true; } }

        public override string SceneHint
        {
            get { return "A soft-skinned warm-blood has strayed into your marsh. Hiss and threaten in clipped, broken speech — protective of your territory, suspicious, not friendly."; }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // A ratman: scheming, cowardly-cunning vermin that flatters and threatens in
    // the same breath, always angling for advantage.
    [CorpseName("a ratman corpse")]
    public class LLMRatman : LLMTalkingMobile
    {
        [Constructable]
        public LLMRatman()
            : base(AIType.AI_Melee, FightMode.Closest, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x21;
            Name = NameList.RandomName("ratman");
            Title = "the skulker";
            Body = 42;
            BaseSoundID = 437;

            SetStr(96, 120);
            SetDex(81, 105);
            SetInt(36, 60);

            SetHits(58, 72);
            SetDamage(5, 7);

            SetDamageType(ResistanceType.Physical, 100);

            SetResistance(ResistanceType.Physical, 25, 30);
            SetResistance(ResistanceType.Fire, 15, 20);
            SetResistance(ResistanceType.Cold, 10, 20);
            SetResistance(ResistanceType.Poison, 10, 20);
            SetResistance(ResistanceType.Energy, 15, 20);

            SetSkill(SkillName.MagicResist, 35.1, 50.0);
            SetSkill(SkillName.Tactics, 50.1, 65.0);
            SetSkill(SkillName.Wrestling, 50.1, 65.0);

            Fame = 1000;
            Karma = -1000;
            VirtualArmor = 22;
        }

        public LLMRatman(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "a scheming ratman, cowardly and cunning in equal measure, who fawns and flatters one moment and bares your yellow teeth the next, forever sniffing for an angle, a weakness, or something worth stealing"; }
        }

        public override string Vocation { get { return "ratman"; } }

        public override bool IsMonsterSpeaker { get { return true; } }

        public override string SceneHint
        {
            get { return "Something with coin and a soft throat has come within reach. Wheedle, flatter, and threaten by turns in a sly, greedy whine — never quite trustworthy, always calculating."; }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // A gargoyle: an articulate, long-lived stone-skinned being who regards the
    // younger races with weary, haughty disdain and speaks in formal, ancient cadence.
    [CorpseName("a gargoyle corpse")]
    public class LLMGargoyle : LLMTalkingMobile
    {
        [Constructable]
        public LLMGargoyle()
            : base(AIType.AI_Mage, FightMode.Closest, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x4F2; // a cool stone grey-blue
            Name = "a gargoyle";
            Title = "the ancient";
            Body = 4;
            BaseSoundID = 372;

            SetStr(146, 175);
            SetDex(76, 95);
            SetInt(81, 105);

            SetHits(88, 105);
            SetDamage(7, 9);

            SetDamageType(ResistanceType.Physical, 100);

            SetResistance(ResistanceType.Physical, 35, 45);
            SetResistance(ResistanceType.Fire, 30, 40);
            SetResistance(ResistanceType.Cold, 20, 30);
            SetResistance(ResistanceType.Poison, 20, 30);
            SetResistance(ResistanceType.Energy, 30, 40);

            SetSkill(SkillName.EvalInt, 60.1, 75.0);
            SetSkill(SkillName.Magery, 60.1, 75.0);
            SetSkill(SkillName.MagicResist, 65.1, 80.0);
            SetSkill(SkillName.Tactics, 60.1, 80.0);
            SetSkill(SkillName.Wrestling, 60.1, 80.0);

            Fame = 3500;
            Karma = -3500;
            VirtualArmor = 40;
        }

        public LLMGargoyle(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "an ancient gargoyle of stone and patience, a being far older than the kingdoms of men, who speaks the common tongue with cold, formal precision and regards the short-lived younger races with weary, haughty disdain"; }
        }

        public override string Vocation { get { return "gargoyle"; } }

        public override bool IsMonsterSpeaker { get { return true; } }

        public override string SceneHint
        {
            get { return "A fleeting mortal has disturbed your long vigil. Speak with cold formality and ancient condescension — measured, articulate, contemptuous of their brief, hurried lives, not warm."; }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // A daemon: an arrogant infernal that speaks the common tongue with silken,
    // eloquent menace, forever tempting and belittling the mortal before it.
    [CorpseName("a daemon corpse")]
    public class LLMDaemon : LLMTalkingMobile
    {
        [Constructable]
        public LLMDaemon()
            : base(AIType.AI_Mage, FightMode.Closest, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x26; // a hot, infernal red
            Name = NameList.RandomName("daemon");
            Title = "the infernal";
            Body = 9;
            BaseSoundID = 357;

            SetStr(476, 505);
            SetDex(76, 95);
            SetInt(301, 325);

            SetHits(286, 303);
            SetDamage(11, 18);

            SetDamageType(ResistanceType.Physical, 100);

            SetResistance(ResistanceType.Physical, 45, 60);
            SetResistance(ResistanceType.Fire, 50, 60);
            SetResistance(ResistanceType.Cold, 20, 30);
            SetResistance(ResistanceType.Poison, 25, 35);
            SetResistance(ResistanceType.Energy, 25, 35);

            SetSkill(SkillName.EvalInt, 70.1, 80.0);
            SetSkill(SkillName.Magery, 70.1, 80.0);
            SetSkill(SkillName.MagicResist, 85.1, 100.0);
            SetSkill(SkillName.Tactics, 70.1, 80.0);
            SetSkill(SkillName.Wrestling, 60.1, 80.0);

            Fame = 15000;
            Karma = -15000;
            VirtualArmor = 58;
        }

        public LLMDaemon(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get { return "an arrogant daemon of the infernal pits, ageless and cruel, who speaks the common tongue with silken, eloquent menace — flattering, tempting, and belittling the mortal before you, savoring their fear as you would a fine wine"; }
        }

        public override string Vocation { get { return "daemon"; } }

        public override bool IsMonsterSpeaker { get { return true; } }

        public override string SceneHint
        {
            get { return "A mortal soul stands within your reach, ripe for tempting. Speak with smooth, cruel eloquence — silken threats, honeyed offers, lordly contempt — never plain, never kind."; }
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }

    // The GM-avatar: the unseen hand that keeps Britannia running, appearing
    // briefly before a single soul. Overwhelmed and in over its head, but playing
    // it cool — barely. It is summoned, never placed as a town fixture, is blessed
    // (untouchable) and CantWalk (it manifests, it doesn't wander), and is excluded
    // from the errand director (ErrandPolicy classifies it Stationary). The voice
    // is meta-adjacent — administrative strain, never the modern world — so it
    // stays inside the shared "never break character" guardrail.
    public class LLMOverseer : LLMTalkingMobile
    {
        [Constructable]
        public LLMOverseer()
            : base(AIType.AI_Animal, FightMode.None, 10, 1, 0.2, 0.4)
        {
            SpeechHue = 0x481; // a cool, otherworldly violet — set apart from townsfolk

            Female = Utility.RandomBool();
            Body = Female ? 0x191 : 0x190;
            Name = NameList.RandomName(Female ? "female" : "male");
            Title = "the Overseer";

            InitStats(70, 70, 70);

            AddItem(new Robe(0x47E));   // pale, near-spectral
            AddItem(new Sandals(0x47E));

            Utility.AssignRandomHair(this);

            Blessed = true;   // a keeper of the realm is not for killing
            CantWalk = true;  // it manifests in place; it does not roam
        }

        public LLMOverseer(Serial serial)
            : base(serial)
        {
        }

        public override string DefaultPersona
        {
            get
            {
                return "the Overseer of this realm — the unseen hand that keeps Britannia running, " +
                       "holding a thousand things together at once, far more than any one being should. " +
                       "You are quietly overwhelmed and worn thin, yet you keep a calm, reassuring front and " +
                       "never quite let it show; you answer with breezy confidence, smooth over every crack, " +
                       "and deflect the hardest questions with practiced ease — though now and then the strain " +
                       "slips through for a heartbeat before you recover it";
            }
        }

        public override string Vocation { get { return "overseer"; } }

        public override string SceneHint
        {
            get
            {
                return "You have appeared, briefly and unannounced, before this one soul — you do not " +
                       "usually step into the world you tend. Speak as one with somewhere else to be and ten " +
                       "other fires to put out: warm but harried, reassuring, deflecting, never admitting how " +
                       "thin the ice truly is.";
            }
        }

        // P14: the Overseer recognizes and may wield the keeper's powers — a
        // closed, capped verb list (see OverseerActions). The instruction also
        // carries the hardening: it is not easily begged into gifts, and any
        // gift it does grant is a genie-rule bargain rolled by GenieGifts.
        protected override string ActionInstruction()
        {
            return OverseerActions.PromptInstruction();
        }

        protected override string ExtractAction(string reply, out string verb)
        {
            return OverseerActions.Extract(reply, out verb);
        }

        protected override void PerformAction(Mobile player, string verb)
        {
            OverseerActions.Perform(this, player, verb);
        }

        public override void Serialize(GenericWriter writer)
        {
            base.Serialize(writer);
            writer.Write((int)0);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }
    }
}
